# Generated by Django 5.0.3 on 2025-04-04 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_category_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(help_text='Select either a main category or a subcategory', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.category'),
        ),
    ]
