# Generated by Django 5.0.3 on 2025-04-04 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='short_description',
            field=models.CharField(blank=True, help_text='Brief description for product listings (max 255 characters)', max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed product description shown on product detail page'),
        ),
    ]
