# Generated by Django 5.0.3 on 2025-04-04 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_productimage_options_productimage_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
