# Generated by Django 5.0.3 on 2025-04-06 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_order_payment_method_order_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('xs', 'Extra Small'), ('s', 'Small'), ('m', 'Medium'), ('l', 'Large'), ('xl', 'Extra Large'), ('xxl', '2XL'), ('3xl', '3XL'), ('4xl', '4XL'), ('5xl', '5XL'), ('one-size', 'One Size'), ('small', 'Small (10cm)'), ('medium', 'Medium (15cm)'), ('large', 'Large (20cm)'), ('custom', 'Custom Size')], max_length=20)),
                ('price_adjustment', models.DecimalField(decimal_places=2, default=0, help_text='Price adjustment for this size (can be positive or negative)', max_digits=10)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kg', max_digits=6, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='store.product')),
            ],
            options={
                'verbose_name': 'Product Size',
                'verbose_name_plural': 'Product Sizes',
                'unique_together': {('product', 'size')},
            },
        ),
        migrations.AddField(
            model_name='cartitem',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.productsize'),
        ),
    ]
